services:
  jamesvilca:
    build: .
    container_name: jamesvilca
    restart: always
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jamesvilca.rule=Host(`jamesvilca.devmotec.com`)"
      - "traefik.http.routers.jamesvilca.entrypoints=websecure"
      - "traefik.http.routers.jamesvilca.tls.certresolver=myresolver"
      - "traefik.http.services.jamesvilca.loadbalancer.server.port=3000"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
